type Col = (u8, u8, u8);

const COLOR_RED: Col = (153, 51, 51);
const DIRT: Col = (151, 109, 77);
const PLANT: Col = (0, 124, 0);
const WOOD: Col = (143, 119, 72);
const COLOR_ORANGE: Col = (216, 127, 51);
const COLOR_GREEN: Col = (102, 127, 51);
const COLOR_BROWN: Col = (102, 76, 51);
const COLOR_YELLOW: Col = (229, 229, 51);
const COLOR_BLACK: Col = (25, 25, 25);
const COLOR_LIGHT_GREEN: Col = (127, 204, 25);
const COLOR_PINK: Col = (242, 127, 165);
const COLOR_PURPLE: Col = (127, 63, 178);
const COLOR_MAGENTA: Col = (178, 76, 216);
const COLOR_LIGHT_BLUE: Col = (102, 153, 216);
const COLOR_CYAN: Col = (76, 127, 153);
const TERRACOTTA_ORANGE: Col = (159, 82, 36);
const TERRACOTTA_CYAN: Col = (87, 92, 92);
const TERRACOTTA_BROWN: Col = (76, 50, 35);
const TERRACOTTA_YELLOW: Col = (186, 133, 36);
const TERRACOTTA_RED: Col = (142, 60, 46);
const TERRACOTTA_LIGHT_GRAY: Col = (135, 107, 98);
const TERRACOTTA_WHITE: Col = (209, 177, 161);
const TERRACOTTA_BLUE: Col = (76, 62, 92);
const TERRACOTTA_PURPLE: Col = (122, 73, 88);
const NETHER: Col = (112, 2, 0);
const GOLD: Col = (250, 238, 77);
const METAL: Col = (167, 167, 167);
const WOOL: Col = (199, 199, 199);
const GLOW_LICHEN: Col = (127, 167, 150);
const STONE: Col = (112, 112, 112);
const WATER: Col = (64, 64, 255);
const GRASS: Col = (127, 178, 56);
const SAND: Col = (247, 233, 163);
const SNOW: Col = (255, 255, 255);
const QUARTZ: Col = (255, 252, 245);
const ICE: Col = (160, 160, 255);
const PODZOL: Col = (129, 86, 49);
const FIRE: Col = (255, 0, 0);
const CLAY: Col = (164, 168, 184);
const CRIMSON_NYLIUM: Col = (189, 48, 49);
const CRIMSON_STEM: Col = (148, 63, 97);
const WARPED_NYLIUM: Col = (22, 126, 134);
const WARPED_STEM: Col = (58, 142, 140);
const WARPED_WART_BLOCK: Col = (20, 180, 133);
const DIAMOND: Col = (92, 219, 213);

/// <https://minecraft.wiki/w/Map_item_format#Color_table>
#[inline]
pub fn get(identifier: impl AsRef<str>) -> Option<(u8, u8, u8)> {
    Some(match identifier.as_ref() {
        "minecraft:water" => WATER,
        "minecraft:grass_block" => GRASS,
        "minecraft:sand" => SAND,
        "minecraft:stone" => STONE,
        "minecraft:dirt" => DIRT,
        "minecraft:gravel" => STONE,
        "minecraft:red_mushroom_block" => COLOR_RED,
        "minecraft:brown_mushroom_block" => DIRT,
        "minecraft:rose_bush" => PLANT,
        "minecraft:dead_bush" => WOOD,
        "minecraft:lilac" => PLANT,
        "minecraft:oxeye_daisy" => PLANT,
        "minecraft:allium" => PLANT,
        "minecraft:lily_of_the_valley" => PLANT,
        "minecraft:pink_tulip" => PLANT,
        "minecraft:white_tulip" => PLANT,
        "minecraft:red_tulip" => PLANT,
        "minecraft:peony" => PLANT,
        "minecraft:azalea" => PLANT,
        "minecraft:beetroots" => PLANT,
        "minecraft:blue_orchid" => PLANT,
        "minecraft:orange_tulip" => PLANT,
        "minecraft:pumpkin_stem" => PLANT,
        "minecraft:attached_pumpkin_stem" => PLANT,
        "minecraft:melon_stem" => PLANT,
        "minecraft:attached_melon_stem" => PLANT,
        "minecraft:lily_pad" => PLANT,
        "minecraft:vine" => PLANT,
        "minecraft:azure_bluet" => PLANT,
        "minecraft:short_grass" => PLANT,
        "minecraft:tall_grass" => PLANT,
        "minecraft:dandelion" => PLANT,
        "minecraft:cornflower" => PLANT,
        "minecraft:poppy" => PLANT,
        "minecraft:sweet_berry_bush" => PLANT,
        "minecraft:sugar_cane" => PLANT,
        "minecraft:fern" => PLANT,
        "minecraft:large_fern" => PLANT,
        "minecraft:wheat" => PLANT,
        "minecraft:carrots" => PLANT,
        "minecraft:potatoes" => PLANT,
        "minecraft:cactus" => PLANT,
        "minecraft:pink_petals" => PLANT,
        "minecraft:sunflower" => PLANT,
        "minecraft:small_dripleaf" => PLANT,
        "minecraft:big_dripleaf" => PLANT,
        "minecraft:flowering_azalea" => PLANT,
        "minecraft:cave_vines_plant" => PLANT,
        "minecraft:pumpkin" => COLOR_ORANGE,
        "minecraft:carved_pumpkin" => COLOR_ORANGE,
        "minecraft:jack_o_lantern" => COLOR_ORANGE,
        "minecraft:melon" => COLOR_LIGHT_GREEN,
        "minecraft:moss_carpet" => COLOR_GREEN,
        "minecraft:moss_block" => COLOR_GREEN,
        "minecraft:mud" => TERRACOTTA_CYAN,
        "minecraft:terracotta" => COLOR_ORANGE,
        "minecraft:orange_terracotta" => TERRACOTTA_ORANGE,
        "minecraft:brown_terracotta" => TERRACOTTA_BROWN,
        "minecraft:yellow_terracotta" => TERRACOTTA_YELLOW,
        "minecraft:red_terracotta" => TERRACOTTA_RED,
        "minecraft:light_gray_terracotta" => TERRACOTTA_LIGHT_GRAY,
        "minecraft:white_terracotta" => TERRACOTTA_WHITE,
        "minecraft:blue_terracotta" => TERRACOTTA_BLUE,
        "minecraft:brown_mushroom" => COLOR_BROWN,
        "minecraft:red_mushroom" => COLOR_RED,
        "minecraft:netherrack" => NETHER,
        "minecraft:magma_block" => NETHER,
        "minecraft:nether_brick_slab" => NETHER,
        "minecraft:bee_nest" => COLOR_YELLOW,
        "minecraft:obsidian" => COLOR_BLACK,
        "minecraft:crying_obsidian" => COLOR_BLACK,
        "minecraft:hay_block" => COLOR_YELLOW,
        "minecraft:crafting_table" => WOOD,
        "minecraft:bell" => GOLD,
        "minecraft:gold_block" => GOLD,
        "minecraft:composter" => WOOD,
        "minecraft:lantern" => METAL,
        "minecraft:mud_bricks" => TERRACOTTA_LIGHT_GRAY,
        "minecraft:mud_brick_slab" => TERRACOTTA_LIGHT_GRAY,
        "minecraft:nether_wart" => COLOR_RED,
        "minecraft:cobweb" => WOOL,
        "minecraft:glow_lichen" => GLOW_LICHEN,
        "minecraft:observer" => STONE,
        "minecraft:kelp" => WATER,
        "minecraft:seagrass" => WATER,
        "minecraft:tall_seagrass" => WATER,
        "minecraft:bubble_column" => WATER,
        "minecraft:snow" => SNOW,
        "minecraft:snow_block" => SNOW,
        "minecraft:powder_snow" => SNOW,
        "minecraft:andesite" => STONE,
        "minecraft:diorite" => QUARTZ,
        "minecraft:diorite_wall" => QUARTZ,
        "minecraft:smooth_quartz_slab" => QUARTZ,
        "minecraft:ice" => ICE,
        "minecraft:packed_ice" => ICE,
        "minecraft:blue_ice" => ICE,
        "minecraft:cherry_leaves" => COLOR_PINK,
        "minecraft:cherry_log" => TERRACOTTA_WHITE,
        "minecraft:calcite" => TERRACOTTA_WHITE,
        "minecraft:dirt_path" => DIRT,
        "minecraft:chest" => WOOD,
        "minecraft:mycelium" => COLOR_PURPLE,
        "minecraft:red_sand" => COLOR_ORANGE,
        "minecraft:podzol" => PODZOL,
        "minecraft:mossy_cobblestone" => STONE,
        "minecraft:coarse_dirt" => DIRT,
        "minecraft:campfire" => PODZOL,
        "minecraft:mangrove_roots" => PODZOL,
        "minecraft:muddy_mangrove_roots" => PODZOL,
        "minecraft:granite" => DIRT,
        "minecraft:coal_ore" => STONE,
        "minecraft:iron_ore" => STONE,
        "minecraft:copper_ore" => STONE,
        "minecraft:emerald_ore" => STONE,
        "minecraft:lapis_ore" => STONE,
        "minecraft:farmland" => DIRT,
        "minecraft:pointed_dripstone" => TERRACOTTA_BROWN,
        "minecraft:dripstone_block" => TERRACOTTA_BROWN,
        "minecraft:lava" => FIRE,
        "minecraft:fire" => FIRE,
        "minecraft:stone_slab" => STONE,
        "minecraft:rooted_dirt" => DIRT,
        "minecraft:clay" => CLAY,
        "minecraft:sea_pickle" => COLOR_GREEN,
        "minecraft:polished_granite" => DIRT,
        "minecraft:red_sandstone" => COLOR_ORANGE,
        "minecraft:smooth_stone" => STONE,
        "minecraft:smooth_stone_slab" => STONE,
        "minecraft:suspicious_gravel" => STONE,
        "minecraft:sandstone" => SAND,
        "minecraft:smooth_sandstone" => SAND,
        "minecraft:smooth_sandstone_stairs" => SAND,
        "minecraft:smooth_sandstone_slab" => SAND,
        "minecraft:cut_sandstone" => SAND,
        "minecraft:sandstone_slab" => SAND,
        "minecraft:sandstone_stairs" => SAND,
        "minecraft:sandstone_wall" => SAND,
        "minecraft:grindstone" => METAL,
        "minecraft:furnace" => STONE,
        "minecraft:stonecutter" => STONE,
        "minecraft:bamboo" => COLOR_YELLOW,
        "minecraft:shulker_box" => COLOR_PURPLE,
        "minecraft:purple_shulker_box" => TERRACOTTA_PURPLE,
        "minecraft:end_stone" => SAND,
        "minecraft:chorus_plant" => COLOR_PURPLE,
        "minecraft:chorus_flower" => COLOR_PURPLE,
        "minecraft:bedrock" => STONE,
        "minecraft:purpur_block" => COLOR_MAGENTA,
        "minecraft:purpur_stairs" => COLOR_MAGENTA,
        "minecraft:purpur_slab" => COLOR_MAGENTA,
        "minecraft:purpur_pillar" => COLOR_MAGENTA,
        "minecraft:end_portal" => COLOR_BLACK,
        "minecraft:dragon_egg" => COLOR_BLACK,
        "minecraft:basalt" => COLOR_BLACK,
        "minecraft:blackstone" => COLOR_BLACK,
        "minecraft:blackstone_wall" => COLOR_BLACK,
        "minecraft:blackstone_slab" => COLOR_BLACK,
        "minecraft:blackstone_stairs" => COLOR_BLACK,
        "minecraft:chiseled_polished_blackstone" => COLOR_BLACK,
        "minecraft:polished_blackstone_slab" => COLOR_BLACK,
        "minecraft:gilded_blackstone" => COLOR_BLACK,
        "minecraft:polished_basalt" => COLOR_BLACK,
        "minecraft:soul_sand" => COLOR_BROWN,
        "minecraft:soul_soil" => COLOR_BROWN,
        "minecraft:glowstone" => SAND,
        "minecraft:nether_quartz_ore" => NETHER,
        "minecraft:crimson_nylium" => CRIMSON_NYLIUM,
        "minecraft:nether_wart_block" => COLOR_RED,
        "minecraft:crimson_roots" => NETHER,
        "minecraft:nether_gold_ore" => NETHER,
        "minecraft:soul_fire" => COLOR_LIGHT_BLUE,
        "minecraft:bone_block" => SAND,
        "minecraft:iron_door" => METAL,
        "minecraft:stone_pressure_plate" => STONE,
        "minecraft:warped_nylium" => WARPED_NYLIUM,
        "minecraft:warped_wart_block" => WARPED_WART_BLOCK,
        "minecraft:warped_roots" => COLOR_CYAN,
        "minecraft:warped_fungus" => COLOR_CYAN,
        "minecraft:warped_stem" => WARPED_STEM,
        "minecraft:twisting_vines" => COLOR_CYAN,
        "minecraft:nether_sprouts" => COLOR_CYAN,
        "minecraft:crimson_fungus" => NETHER,
        "minecraft:crimson_stem" => CRIMSON_STEM,
        "minecraft:crimson_planks" => CRIMSON_STEM,
        "minecraft:crimson_slab" => CRIMSON_STEM,
        "minecraft:shroomlight" => COLOR_RED,
        "minecraft:nether_bricks" => NETHER,
        "minecraft:nether_brick_fence" => NETHER,
        "minecraft:nether_brick_stairs" => NETHER,
        "minecraft:spawner" => STONE,
        "minecraft:brick_slab" => COLOR_RED,
        "minecraft:lightning_rod" => COLOR_ORANGE,
        "minecraft:decorated_pot" => TERRACOTTA_RED,
        "minecraft:iron_block" => METAL,
        "minecraft:chiseled_sandstone" => SAND,
        "minecraft:beacon" => DIAMOND,
        "minecraft:barrel" => WOOD,
        "minecraft:diorite_stairs" => QUARTZ,
        "minecraft:sea_lantern" => QUARTZ,
        "minecraft:diamond_ore" => STONE,
        "minecraft:cyan_terracotta" => TERRACOTTA_CYAN,
        // Saplings and leaves before woods
        b if b.ends_with("sapling") => PLANT,
        b if b.ends_with("leaves") => PLANT,
        // All wood types
        b if b.contains("dark_oak") => COLOR_BROWN,
        b if b.contains("oak") => WOOD,
        b if b.contains("acacia") => COLOR_ORANGE,
        b if b.contains("birch") => SAND,
        b if b.contains("spruce") => PODZOL,
        b if b.contains("mangrove") => COLOR_RED,
        b if b.contains("jungle") => DIRT,
        b if b.contains("stone_brick") => STONE,
        b if b.contains("cobblestone") => STONE,
        b if b.contains("copper") => COLOR_ORANGE,
        // Banners before colors, because they are all WOOD
        b if b.ends_with("banner") => WOOD,
        // Colors
        b if b.contains("white") => SNOW,
        b if b.contains("yellow") => COLOR_YELLOW,
        b if b.contains("red") => COLOR_RED,
        b if b.contains("magenta") => COLOR_MAGENTA,
        // TODO: colorize corals
        b if b.contains("coral") => WATER,
        b => {
            #[cfg(feature = "bevy")]
            bevy::log::info!("unknown map color for: {b}");
            return None;
        }
    })
}
